---
version: "3"

services:
  3x-ui:
    image: test:latest
    container_name: 3x-ui
    hostname: yourhostname
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      WEB_BASE_PATH: "/control/"
    tty: true
    network_mode: bridge
    ports:
      - "2067:2067"  # Проброс порта
    restart: unless-stopped
